version: '3.8'
services:
  backend:
    build: ./back
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./back/data:/app/data
      - ./back:/app
  frontend:
    build: ./front
    container_name: rag-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend 